export enum LOCAL_STORAGE_ITEM_KEY {
  // 需加密
  ACCESS_TOKEN = 'xd7w2nS67zXbM7n4',
  ROLE_TOKEN = 'CK3cp7PDvzRSKNqv',
  USER_ROLE = 'hyPGGDxUVEUFeMEX',
  USER_INFO = 'v93MNkQNhY2Vr9Dg',
  USER_ROLE_IN_NETWORK = 'mYg3TyCAwevWRfSD',
  LEAGUE_NAME = 'S7hRAwmx5mkWebNW',
  NETWORK_NAME = 'qpRVy2PNXMYndyac',
  // 无加密
  COMMON_PORTAL_SELECTED_MENU = 'HKMVQactRt4kSNER',
  NETWORK_PORTAL_SELECTED_MENU = 'RFEVeXYKHv96skMh',
  DRAWER_CURRENT_SERVICE = 'SDJVHjbhd2153sfgfergRE',
  NEW_ACCOUNT_LOGIN = 'H8GctsRtstd25W5f'
}